// Easy questions for Wrong Answers Only game
// Players must answer these questions incorrectly
export const WRONG_ANSWERS_QUESTIONS = [
  "What color is the sky?",
  "How many legs does a cat have?",
  "What do you use to write?",
  "What animal says 'woof'?",
  "What is 2 + 2?",
  "What do you wear on your feet?",
  "What do you drink when you're thirsty?",
  "What time is lunch usually eaten?",
  "What shape is a ball?",
  "How many eyes do you have?",
  "What do you use to brush your teeth?",
  "What comes after Monday?",
  "What color is grass?",
  "What do birds use to fly?",
  "What is the opposite of hot?",
  "How many fingers on one hand?",
  "What do you use to see?",
  "What animal lives in the ocean?",
  "What do you say when you meet someone?",
  "What is the first letter of the alphabet?",
  "What do you use to eat soup?",
  "What color is snow?",
  "How many days in a week?",
  "What do you wear on your head?",
  "What animal says 'meow'?",
  "What is 5 - 3?",
  "What do you use to open a door?",
  "What color is the sun?",
  "How many months in a year?",
  "What do you use to tell time?",
  "What shape has four equal sides?",
  "What do you use to cut paper?",
  "What animal says 'moo'?",
  "What is the opposite of day?",
  "How many wheels on a bicycle?",
  "What do you use to hear?",
  "What color are bananas?",
  "What do you use to sleep?",
  "What is 3 + 3?",
  "What animal has a trunk?",
  "What do you use to wash your hands?",
  "What color is fire?",
  "How many seasons are there?",
  "What do you use to read?",
  "What animal says 'quack'?",
  "What is the opposite of big?",
  "How many sides does a triangle have?",
  "What do you use to smell?",
  "What color are apples?",
  "What do you use to sit?",
  "What is 10 - 5?",
  "What animal lives on a farm?",
  "What do you use to write on paper?",
  "What color is chocolate?",
  "How many hours in a day?",
  "What do you use to walk?",
  "What animal says 'oink'?",
  "What is the opposite of up?",
  "How many corners does a square have?",
  "What do you use to taste?",
  "What color are carrots?",
  "What do you use to cook?",
  "What is 4 + 4?",
  "What animal has stripes?",
  "What do you use to clean?",
  "What color is milk?",
  "How many minutes in an hour?",
  "What do you use to jump?",
  "What animal says 'neigh'?",
  "What is the opposite of fast?",
  "How many sides does a circle have?",
  "What do you use to touch?",
  "What color are strawberries?",
  "What do you use to play music?",
  "What is 6 + 2?",
  "What animal has a long neck?",
  "What do you use to dry off?",
  "What color is the moon?",
  "How many seconds in a minute?",
  "What do you use to run?",
  "What animal says 'baa'?",
  "What is the opposite of happy?",
  "How many sides does a pentagon have?",
  "What do you use to feel?",
  "What color are oranges?",
  "What do you use to watch shows?",
  "What is 8 - 2?",
  "What animal has wings?",
  "What do you use to stay warm?",
  "What color is a stop sign?",
  "How many days in February?",
  "What do you use to climb?",
  "What animal lives in a tree?",
  "What is the opposite of light?",
  "How many sides does a hexagon have?",
  "What do you use to balance?",
  "What color are grapes?",
  "What do you use to talk?",
  "What is 5 + 5?",
  "What animal has a shell?",
];

/**
 * Get a random question from the questions list
 * @returns A random question string
 */
export function getRandomQuestion(): string {
  const randomIndex = Math.floor(Math.random() * WRONG_ANSWERS_QUESTIONS.length);
  return WRONG_ANSWERS_QUESTIONS[randomIndex];
}

